server:
  port: 8082

spring:
  application:
    name: microservice-payment

  kafka:
    bootstrap-servers: localhost:9092
    topic: payment-events

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
