server:
  port: 8083

spring:
  application:
    name: microservice-inventory

  redis:
    host: localhost
    port: 6379

resilience4j:
  bulkhead:
    instances:
      inventoryService:
        maxConcurrentCalls: 10
        maxWaitDuration: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
